### ISSUE TITLE
Can you not rely on guava?

### ISSUE THREAD

**Issue by thecatcore** [Chocohead/Fabric-ASM#20]
It's conflicting with an old version of guava (12.0.1) used by forge in 1.3.2.
Using newer guava simply breaks forge.

Necessary for my project [Fabricated-Legacy-Forge](https://github.com/arthurbambou/Fabricated-Legacy-Forge)

**Comment by thecatcore** [comment]
Stacktrace:
```
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Maps.asMap(Ljava/util/Set;Lcom/google/common/base/Function;)Ljava/util/Map;
	at com.chocohead.mm.Plugin$2.putAll(Plugin.java:182)
	at com.google.common.collect.ForwardingMap.putAll(ForwardingMap.java:110)
	at com.chocohead.mm.api.ClassTinkerers.hookUp(ClassTinkerers.java:53)
	at com.chocohead.mm.Plugin.onLoad(Plugin.java:238)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 18 more
```
