### ISSUE TITLE
Java 17 Sealed Enchantment Target

### ISSUE THREAD

**Issue by Zev1nn** [Chocohead/Fabric-ASM#22]
EnchantmentTarget as of Java 17 is considered a sealed class so this crash can occour if you are using Java 17

 net.fabricmc.loader.impl.FormattedException: java.lang.IncompatibleClassChangeError: class net.minecraft.enchantment.EnchantmentTarget$15 cannot inherit from sealed class net.minecraft.enchantment.EnchantmentTarget
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.IncompatibleClassChangeError: class net.minecraft.enchantment.EnchantmentTarget$15 cannot inherit from sealed class net.minecraft.enchantment.EnchantmentTarget
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.enchantment.ProtectionEnchantment.<init>(ProtectionEnchantment.java:37) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at net.minecraft.enchantment.Enchantments.<clinit>(Enchantments.java:16) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at net.minecraft.registry.Registries.method_47471(Registries.java:121) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at net.minecraft.registry.Registries.method_47485(Registries.java:210) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at net.minecraft.registry.Registries.method_47482(Registries.java:225) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.registry.Registries.init(Registries.java:223) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at net.minecraft.Bootstrap.redirect$zip000$fabric-registry-sync-v0$initialize(Bootstrap.java:565) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:61) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:154) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	... 3 more

**Comment by hugeblank** [comment]
duplicate of #11
